improve the syntax

diff --git a/.github/workflows/validation.yaml b/.github/workflows/validation.yaml
--- a/.github/workflows/validation.yaml
+++ b/.github/workflows/validation.yaml
@@ -274,13 +274,12 @@ jobs:
         run: python src/util/update_data.py
       - name: Run binary
         run: |
-          cargo run
-          if [ "$?" -ne 0 ]; then
-            echo 'DEBUG: Binary failed to execute'
+          cargo run || {
+            echo 'DEBUG: binary failed to execute'
             RUST_BACKTRACE=1 cargo run --verbose --verbose
-            echo 'DEBUG: Exiting the workflow'
+            echo 'DEBUG: exiting the workflow'
             exit 1
-          fi
+          }
       - name: Hash output
         run: sha256sum output/*
       - name: Upload output artifact
